import React, { useState } from 'react';
import { Tag, Check, RefreshCw, DollarSign } from 'lucide-react';
import { PlanType, PLAN_LABELS, DEFAULT_PRICES } from '../types';

interface PriceSettingsProps {
  pricesData: Record<string, number>;
  onUpdatePrice: (plan: PlanType, price: number) => Promise<void>;
}

export const PriceSettings: React.FC<PriceSettingsProps> = ({ pricesData, onUpdatePrice }) => {
  const plans: PlanType[] = ['5H', '1D', '3D', '7D', '15D', '30D', '60D'];
  const [localPrices, setLocalPrices] = useState<Record<string, string>>({});
  const [savingPlan, setSavingPlan] = useState<string | null>(null);

  const handlePriceChange = (plan: PlanType, val: string) => {
    setLocalPrices((prev) => ({ ...prev, [plan]: val }));
  };

  const handleSave = async (plan: PlanType) => {
    const raw = localPrices[plan] ?? String(pricesData[plan] ?? DEFAULT_PRICES[plan]);
    const num = parseFloat(raw);
    if (isNaN(num) || num < 0) return;

    setSavingPlan(plan);
    try {
      await onUpdatePrice(plan, num);
    } finally {
      setSavingPlan(null);
    }
  };

  return (
    <div className="space-y-6 animate-fadeIn">
      <div className="bg-slate-900 border border-slate-800/80 rounded-2xl p-6 shadow-xl space-y-4">
        <div className="flex items-center gap-3 pb-3 border-b border-slate-800">
          <div className="w-10 h-10 rounded-xl bg-amber-500/10 border border-amber-500/30 flex items-center justify-center text-amber-400">
            <Tag className="w-5 h-5" />
          </div>
          <div>
            <h3 className="font-display text-lg font-bold text-white">Plan Pricing Control</h3>
            <p className="text-xs text-slate-400">
              Configure cost in ₹ per key generated by resellers. Changes take effect instantly.
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {plans.map((p) => {
            const currentPrice = pricesData[p] ?? DEFAULT_PRICES[p];
            const inputValue = localPrices[p] ?? String(currentPrice);

            return (
              <div
                key={p}
                className="p-5 rounded-xl bg-slate-950 border border-slate-800/80 hover:border-slate-700 transition-all space-y-3"
              >
                <div className="flex items-center justify-between">
                  <span className="font-display font-bold text-white text-base">{p}</span>
                  <span className="text-xs text-slate-400">{PLAN_LABELS[p]}</span>
                </div>

                <div className="flex items-center gap-2">
                  <div className="relative flex-1">
                    <span className="absolute left-3 top-1/2 -translate-y-1/2 text-emerald-400 font-bold text-sm">
                      ₹
                    </span>
                    <input
                      type="number"
                      min={0}
                      step={0.5}
                      value={inputValue}
                      onChange={(e) => handlePriceChange(p, e.target.value)}
                      className="w-full pl-8 pr-3 py-2 bg-slate-900 border border-slate-800 rounded-xl text-sm font-bold text-white font-mono focus:outline-none focus:border-amber-500"
                    />
                  </div>
                  <button
                    onClick={() => handleSave(p)}
                    disabled={savingPlan === p}
                    className="p-2.5 rounded-xl bg-amber-600 hover:bg-amber-500 disabled:opacity-50 text-white transition-colors"
                    title="Update Price"
                  >
                    <Check className="w-4 h-4" />
                  </button>
                </div>

                <div className="text-[11px] text-slate-500 flex justify-between">
                  <span>Current Active Rate:</span>
                  <strong className="text-emerald-400 font-mono">₹{currentPrice.toFixed(2)}</strong>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};
